/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-111115-g8e21f32fe7-20230618"
#endif /* AVUTIL_FFVERSION_H */
